Demonstrate failing to read a vector
This will fail since the index is too big.

```
thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 100', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/slice/mod.rs:2842:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```